#!/usr/bin/env ruby

# TODO: make sure no matching containers are
#       running before attempting removal
def remove_containers(args)
  puts "\n"
  containers = `docker ps -aqf name=#{args}` # String
  containers = containers.split(/\n/) # Array
  unless containers.empty?
    puts "removing containers that match: #{args}"
    # TODO: remove false message of "container x was removed"
    #       when container x wasn't actually removed
    #       e.g. if the container is still running
    containers.map do |c|
      `docker container rm #{c}`
      puts "container #{c} was removed"
    end
  else
    puts "no containers removed: no containers match #{args}"
  end
end

def remove_volumes(args)
  puts "\n"
  volumes = `docker volume ls` # String
  volumes = volumes.squeeze(' ').chop
  volumes = volumes.split(/\nlocal /) # Array
  volumes = volumes.map do |v|
    if v.match(args)
      v
    end
  end
  volumes = volumes.compact # remove any lingering nil values
  unless volumes.empty?
    puts "removing volumes that match: #{args}"
    volumes.map do |v|
      `docker volume rm #{v}`
      puts "volume #{v} was removed"
    end
  else
    puts "no volumes removed: no volumes match #{args}"
  end
end

unless ARGV.length == 0
  ARGV.each do |value|
    puts "\n"
    puts "I, the mighty " + File.basename(__FILE__) + ", was passed: " + value
    remove_containers(value)
    remove_volumes(value)
    puts "\n--------------------------------------------------------------------"
  end
else
  puts "Please pass an argument"
end
